[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.79.0"

[context]
[context.branch-deploy]
command = "hugo --gc --minify -b $URL"
[context.deploy-preview]
command = "hugo --gc --minify -b $URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
